# Generated by Django 5.0.12 on 2025-02-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_category_options_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
