# Generated by Django 5.0.12 on 2025-02-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_category_type_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('IN', 'Receita'), ('EX', 'Despesa')], max_length=2),
        ),
    ]
