# Generated by Django 5.0.12 on 2025-02-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_category_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='transaction_type',
            new_name='category_type',
        ),
    ]
