# Generated by Django 5.0.12 on 2025-02-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_expense_user_remove_income_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CA', 'Dinheiro'), ('CC', 'Cartão de Crédito'), ('DC', 'Cartão de Débito'), ('PX', 'PIX'), ('TR', 'Transferência Bancária'), ('BL', 'Boleto Bancário'), ('CH', 'Cheque'), ('OT', 'Outro')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('CA', 'Dinheiro'), ('CC', 'Cartão de Crédito'), ('DC', 'Cartão de Débito'), ('PX', 'PIX'), ('TR', 'Transferência Bancária'), ('BL', 'Boleto Bancário'), ('CH', 'Cheque'), ('OT', 'Outro')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
