# Generated by Django 5.0.12 on 2025-02-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_expense_payment_method_income_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PD', 'Pendente'), ('PA', 'Pago'), ('CA', 'Cancelado'), ('OV', 'Atrasado')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
