# Generated by Django 5.0.12 on 2025-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_expense_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('PD', 'Pendente'), ('PA', 'Pago'), ('CA', 'Cancelado'), ('OV', 'Atrasado')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
