# Generated by Django 5.0.12 on 2025-04-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_expense_balance_income_balance_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Recorrente?'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da recorrência'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('DA', 'Diário'), ('WE', 'Semanal'), ('MO', 'Mensal')], default='', max_length=10, verbose_name='Frequência da recorrência'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_start',
            field=models.DateField(blank=True, null=True, verbose_name='Início da recorrência'),
        ),
        migrations.AddField(
            model_name='income',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Recorrente?'),
        ),
        migrations.AddField(
            model_name='income',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da recorrência'),
        ),
        migrations.AddField(
            model_name='income',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('DA', 'Diário'), ('WE', 'Semanal'), ('MO', 'Mensal')], default='', max_length=10, verbose_name='Frequência da recorrência'),
        ),
        migrations.AddField(
            model_name='income',
            name='recurrence_start',
            field=models.DateField(blank=True, null=True, verbose_name='Início da recorrência'),
        ),
        migrations.DeleteModel(
            name='RecurringTransaction',
        ),
    ]
