# Generated by Django 5.0.12 on 2025-04-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_expense_is_recurring_expense_recurrence_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('DA', 'Diário'), ('WE', 'Semanal'), ('MO', 'Mensal'), ('YE', 'Anual')], default='', max_length=10, verbose_name='Frequência da recorrência'),
        ),
        migrations.AlterField(
            model_name='income',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('DA', 'Diário'), ('WE', 'Semanal'), ('MO', 'Mensal'), ('YE', 'Anual')], default='', max_length=10, verbose_name='Frequência da recorrência'),
        ),
    ]
