# Generated by Django 5.0.12 on 2025-04-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_expense_recurrence_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='recurrence_end',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='recurrence_start',
        ),
        migrations.RemoveField(
            model_name='income',
            name='recurrence_end',
        ),
        migrations.RemoveField(
            model_name='income',
            name='recurrence_start',
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Repetições'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término da Recorrência'),
        ),
        migrations.AddField(
            model_name='income',
            name='recurrence_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Repetições'),
        ),
        migrations.AddField(
            model_name='income',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término da Recorrência'),
        ),
    ]
