# Generated by Django 5.0.12 on 2025-05-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_remove_expense_recurrence_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='transactions.expense', verbose_name='Transação Pai'),
        ),
        migrations.AddField(
            model_name='income',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='transactions.income', verbose_name='Transação Pai'),
        ),
    ]
