# Generated by Django 5.0.12 on 2025-04-11 14:06

import sisgef.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mês')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Receitas')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Despesas')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Final')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sisgef.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sisgef.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Saldo Mensal',
                'verbose_name_plural': 'Saldos Mensais',
                'unique_together': {('month', 'year')},
            },
        ),
    ]
